#!/bin/bash
# set -x

git submodule update --init --recursive

PLATFORM=`uname -m`"_"`uname -s`

error () {
    echo "ERROR:"
    tail -n 5 build.log
    exit 1
}

# make c compiler
echo "Making CC for ${PLATFORM} .."
cd mcc || exit 1
make clean > ../build.log || exit 1
make "ARCH=${PLATFORM}" all >> ../build.log || error
cd .. || exit 1

if test -z "${1}" ; then
    echo No file specified, exiting
    exit 0
fi

#compile
echo "Running CC, '${1}' .."
cp "./mcc/arch/${PLATFORM}/header.s"  "am/program_${PLATFORM}.s" || exit 1
cc -E "${1}" | grep -v '^#' | ./mcc/mcc >> "am/program_${PLATFORM}.s" 2>> build.log || error
# cat "./mcc/arch/${PLATFORM}/footer.s" >> "am/program_${PLATFORM}.s" || exit 1

gcc -c -o "am/program_${PLATFORM}.o" "am/program_${PLATFORM}.s" 2>> build.log || error
ld -o unix_prog.bin "am/program_${PLATFORM}.o" 2>> build.log || error

echo "SUCCESS"
exit 0

