#!/bin/bash
# set -x

# make c compiler
echo "Making CC .."
cd mcc || exit 1
make clean > ../build.log || exit 1
make ARCH=x86_64 all >> ../build.log || exit 1
cd .. || exit 1

if test -z "${1}" ; then
    echo No file specified, exiting
    exit 0
fi

#compile
echo "Running CC, '${1}' .."
cp ./mcc/arch/x86_64/header.s  am/program.s || exit 1
cc -E "${1}" | grep -v '^#' | ./mcc/mcc >> am/program.s 2>> build.log || exit 1
# cat ./mcc/arch/x86_64/footer.s >> am/program.s || exit 1

gcc -c -o am/program.o am/program.s || exit 1
ld -o x86_64_prog.bin am/program.o || exit 1



